version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/magento
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 1200
      runas: root

